import moment from 'moment';

export const allTime = new Date(moment.unix(0).toString());
export const yesterday = moment().add(-1, 'day').startOf('day').toString();
export const lastWeek = moment().add(-7, 'day').startOf('day').toString();
export const lastThirtyDays = moment().add(-30, 'day').startOf('day').toString();
export const thisMonth = moment().startOf('month').toString();
export const lastDayLastMonth = moment().add(-1, 'month').endOf('month').toString();
export const lastMonth = moment().add(-1, 'month').startOf('month').toString();
export const now = new Date(moment().endOf('day').toString());

export const users: User[] = [
  {
    userId: 1,
    name: 'User1',
    email: 'user@user.com',
    block: false,
    signInDate: '1/1/2020',
    lastActivity: '03/21/2020',
    lastAction: 'view_landing_course1',
    product: 'Как наладить отнош',
  },
  {
    userId: 2,
    name: 'User2',
    email: 'user@user.com',
    block: false,
    signInDate: '1/01/2020',
    lastActivity: '02/11/2020',
    lastAction: 'view_landing_course1',
    product: 'Как наладить отнош',
  },
  {
    userId: 3,
    name: 'User3',
    email: 'user@user.com',
    block: false,
    signInDate: '1/03/2020',
    lastActivity: '03/01/2020',
    lastAction: 'view_landing_course1',
    product: 'Как наладить отнош',
  },
  {
    userId: 4,
    name: 'User4',
    email: 'user@user.com',
    block: false,
    signInDate: '1/02/2020',
    lastActivity: '03/18/2020',
    lastAction: 'view_landing_course1',
    product: 'Как наладить отнош',
  },
  {
    userId: 6,
    name: 'User6',
    email: 'user@user.com',
    block: false,
    signInDate: '1/01/2020',
    lastActivity: '03/05/2020',
    lastAction: 'view_landing_course1',
    product: 'Как наладить отнош',
  },
  {
    userId: 5,
    name: 'User5',
    email: 'user@user.com',
    block: false,
    signInDate: '1/02/2020',
    lastActivity: '02/20/2020',
    lastAction: 'view_landing_course1',
    product: 'Как наладить отнош',
  },
  {
    userId: 7,
    name: 'User7',
    email: 'user@user.com',
    block: true,
    signInDate: '1/03/2020',
    lastActivity: '03/03/2020',
    lastAction: 'view_landing_course1',
    product: 'Как наладить отнош',
  },
  {
    userId: 8,
    name: 'User8',
    email: 'user@user.com',
    block: false,
    signInDate: '1/02/2020',
    lastActivity: '02/26/2020',
    lastAction: 'view_landing_course1',
    product: 'Как наладить отнош',
  },
  {
    userId: 9,
    name: 'User9',
    email: 'user@user.com',
    block: false,
    signInDate: '03/03/2020',
    lastActivity: '03/21/2020',
    lastAction: 'view_landing_course1',
    product: 'Как наладить отнош',
  },
  {
    userId: 10,
    name: 'User10',
    email: 'user@user.com',
    block: false,
    signInDate: '02/02/2020',
    lastActivity: '02/20/2020',
    lastAction: 'view_landing_course1',
    product: 'Как наладить отнош',
  },
  {
    userId: 11,
    name: 'User11',
    email: 'user@user.com',
    block: false,
    signInDate: '03/01/2020',
    lastActivity: '03/21/2020',
    lastAction: 'view_landing_course1',
    product: 'Как наладить отнош',
  },
  {
    userId: 12,
    name: 'User12',
    email: 'user@user.com',
    block: false,
    signInDate: '1/01/2020',
    lastActivity: '01/06/2020',
    lastAction: 'view_landing_course1',
    product: 'Как наладить отнош',
  },
  {
    userId: 13,
    name: 'User13',
    email: 'user@user.com',
    block: false,
    signInDate: '03/01/2020',
    lastActivity: '03/01/2020',
    lastAction: 'view_landing_course1',
    product: 'Как наладить отнош',
  },
  {
    userId: 14,
    name: 'User14',
    email: 'user@user.com',
    block: false,
    signInDate: '02/01/2020',
    lastActivity: '03/01/2020',
    lastAction: 'view_landing_course1',
    product: 'Как наладить отнош',
  },
  {
    userId: 15,
    name: 'User15',
    email: 'user@user.com',
    block: false,
    signInDate: '1/01/2020',
    lastActivity: '01/21/2020',
    lastAction: 'view_landing_course1',
    product: 'Как наладить отнош',
  },
  {
    userId: 16,
    name: 'User16',
    email: 'user@user.com',
    block: false,
    signInDate: '1/02/2020',
    lastActivity: '03/02/2020',
    lastAction: 'view_landing_course1',
    product: 'Как наладить отнош',
  },
];

export const ru: Ru = {
  firstDayOfWeek: 1,
  dayNames: ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'],
  dayNamesShort: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
  dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
  monthNames: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
  monthNamesShort: ['янв', 'фев', 'мар', 'апр', 'май', 'июн', 'июл', 'авг', 'сен', 'окт', 'ноя', 'дек'],
  today: 'Hoy',
  clear: 'Limpiar',
  dateFormat: 'dd/mm/yy',
  weekHeader: 'Sm',
};
